### PR TITLE
Add RECS questionnaire to bib

### PR DESCRIPTION
**Pull request by ivelasq**

### CODE REVIEW

**Review by szimmer — COMMENTED** [review]
Why do you have the publication date of 2023? It would've been 2020 or earlier.

**Comment by ivelasq** [comment]
@szimmer weren't the 2020 docs released in 2023?

**Comment by szimmer** [comment]
No I don't think so. I can already see the 2024 version online. These are released when they're approved, I am guessing

**Comment by ivelasq** [comment]
Got it. Changed to 2020!

**Review by szimmer — APPROVED** [review]

**Pull request merged**
